### ISSUE TITLE
Support `base-4.17.1.0` (which ships with `ghc`, version 9.4.5.)

### ISSUE THREAD

**Issue by soenkehahn** [laserpants/hashids-haskell#14]
Currently the `package.yaml` file says `base >=4.9 && <4.17`, however `ghc` 9.4.5 ships with a newer base version. It'd be nice if that version was supported.

**Comment by laserpants** [comment]
Thanks for the suggestion! I have [updated the package](https://github.com/laserpants/hashids-haskell/commit/cdf47c5c83cfcf18c53af56a0e886bed346d5114) and pushed a new version to Hackage here: [hashids-1.1.0.0](https://hackage.haskell.org/package/hashids-1.1.0.0)

@soenkehahn: You may also be interested to know that there is work in progress (by the original author of Hashids) on a new version of this library, known as "Sqids". The Haskell port is already available. The official Sqids website is here: https://sqids.org/ and the Haskell version can be found [here](https://github.com/sqids/sqids-haskell) and on [Hackage](https://hackage.haskell.org/package/sqids). Feedback and suggestions are greatly appreciated. You can find details of the algorithm [here](https://github.com/sqids/sqids-spec). Hashids will still be maintained however.

**Comment by soenkehahn** [comment]
@laserpants: Thanks for the quick fix! That's great!

It seems that the `package.yaml` file has the current version, but the `hashids.cabal` file on current master still has the old version `1.0.2.7`.

**Comment by laserpants** [comment]
@soenkehahn: Ooops! Looks like I had missed to commit that file. :man_facepalming:  I added it [here](https://github.com/laserpants/hashids-haskell/commit/250ea894ff07392061c639fb977d00db048c170b) and uploaded a new version as 1.1.0.1. Please try this one instead: https://hackage.haskell.org/package/hashids-1.1.0.1.
