### ISSUE TITLE
Stackage inclusion

### ISSUE THREAD

**Issue by rvion** [laserpants/hashids-haskell#3]
Hello, would you agree to put this library in [Stackage](https://www.stackage.org/) ?

https://github.com/fpco/stackage/edit/master/build-constraints.yaml

**Comment by laserpants** [comment]
Hi. Thanks for reaching out and sorry for the delay. I noticed that my tests were not included in the cabal package, so I have added them now and created the pull request. Not sure if I got the format and everything right, but let's see.
